-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MLP_MLP_Pipeline_VITIS_LOOP_123_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_layer_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_layer_ce0 : OUT STD_LOGIC;
    output_layer_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_layer_casted_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_layer_casted_ce0 : OUT STD_LOGIC;
    output_layer_casted_we0 : OUT STD_LOGIC;
    output_layer_casted_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2471_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2471_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2471_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2471_p_ce : OUT STD_LOGIC );
end;


architecture behav of MLP_MLP_Pipeline_VITIS_LOOP_123_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_4B189680 : STD_LOGIC_VECTOR (31 downto 0) := "01001011000110001001011010000000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln123_fu_107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_4_cast_fu_119_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_4_cast_reg_280 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_4_cast_reg_280_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_4_cast_reg_280_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_4_cast_reg_280_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal i_4_cast_reg_280_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal output_layer_load_reg_290 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_295 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_64 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln123_fu_113_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (2 downto 0);
    signal data_V_fu_129_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_1_fu_150_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_154_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_V_fu_140_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln346_fu_168_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln346_fu_172_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1512_fu_186_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal isNeg_fu_178_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1512_fu_192_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ush_fu_196_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1488_fu_204_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_164_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln1488_fu_208_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_fu_212_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_fu_224_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_1_fu_218_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln818_fu_232_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_236_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_246_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_132_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_V_2_fu_254_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component MLP_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MLP_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component MLP_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln123_fu_107_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_64 <= add_ln123_fu_113_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_64 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    i_4_cast_reg_280_pp0_iter1_reg(2 downto 0) <= i_4_cast_reg_280(2 downto 0);
                output_layer_load_reg_290 <= output_layer_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                dc_reg_295 <= grp_fu_2471_p_dout0;
                    i_4_cast_reg_280_pp0_iter2_reg(2 downto 0) <= i_4_cast_reg_280_pp0_iter1_reg(2 downto 0);
                    i_4_cast_reg_280_pp0_iter3_reg(2 downto 0) <= i_4_cast_reg_280_pp0_iter2_reg(2 downto 0);
                    i_4_cast_reg_280_pp0_iter4_reg(2 downto 0) <= i_4_cast_reg_280_pp0_iter3_reg(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_107_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    i_4_cast_reg_280(2 downto 0) <= i_4_cast_fu_119_p1(2 downto 0);
            end if;
        end if;
    end process;
    i_4_cast_reg_280(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    i_4_cast_reg_280_pp0_iter1_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    i_4_cast_reg_280_pp0_iter2_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    i_4_cast_reg_280_pp0_iter3_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    i_4_cast_reg_280_pp0_iter4_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln123_fu_113_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv3_1));
    add_ln346_fu_172_p2 <= std_logic_vector(unsigned(zext_ln346_fu_168_p1) + unsigned(ap_const_lv9_181));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln123_fu_107_p2)
    begin
        if (((icmp_ln123_fu_107_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_64, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_64;
        end if; 
    end process;

    data_V_fu_129_p1 <= dc_reg_295;
    grp_fu_2471_p_ce <= ap_const_logic_1;
    grp_fu_2471_p_din0 <= output_layer_load_reg_290;
    grp_fu_2471_p_din1 <= ap_const_lv32_4B189680;
    i_4_cast_fu_119_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_4),64));
    icmp_ln123_fu_107_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv3_5) else "0";
    isNeg_fu_178_p3 <= add_ln346_fu_172_p2(8 downto 8);
    mantissa_fu_154_p4 <= ((ap_const_lv1_1 & p_Result_1_fu_150_p1) & ap_const_lv1_0);
    output_layer_address0 <= i_4_cast_fu_119_p1(3 - 1 downto 0);
    output_layer_casted_address0 <= i_4_cast_reg_280_pp0_iter4_reg(3 - 1 downto 0);

    output_layer_casted_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            output_layer_casted_ce0 <= ap_const_logic_1;
        else 
            output_layer_casted_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_layer_casted_d0 <= 
        result_V_2_fu_254_p2 when (p_Result_s_fu_132_p3(0) = '1') else 
        val_fu_246_p3;

    output_layer_casted_we0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            output_layer_casted_we0 <= ap_const_logic_1;
        else 
            output_layer_casted_we0 <= ap_const_logic_0;
        end if; 
    end process;


    output_layer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_layer_ce0 <= ap_const_logic_1;
        else 
            output_layer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_1_fu_150_p1 <= data_V_fu_129_p1(23 - 1 downto 0);
    p_Result_s_fu_132_p3 <= data_V_fu_129_p1(31 downto 31);
    r_V_1_fu_218_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_164_p1),to_integer(unsigned('0' & zext_ln1488_fu_208_p1(31-1 downto 0)))));
    r_V_fu_212_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_164_p1),to_integer(unsigned('0' & zext_ln1488_fu_208_p1(31-1 downto 0)))));
    result_V_2_fu_254_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_fu_246_p3));
        sext_ln1488_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_fu_196_p3),32));

        sext_ln1512_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1512_fu_186_p2),9));

    sub_ln1512_fu_186_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_V_fu_140_p4));
    tmp_6_fu_236_p4 <= r_V_1_fu_218_p2(55 downto 24);
    tmp_fu_224_p3 <= r_V_fu_212_p2(24 downto 24);
    ush_fu_196_p3 <= 
        sext_ln1512_fu_192_p1 when (isNeg_fu_178_p3(0) = '1') else 
        add_ln346_fu_172_p2;
    val_fu_246_p3 <= 
        zext_ln818_fu_232_p1 when (isNeg_fu_178_p3(0) = '1') else 
        tmp_6_fu_236_p4;
    xs_exp_V_fu_140_p4 <= data_V_fu_129_p1(30 downto 23);
    zext_ln1488_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1488_fu_204_p1),79));
    zext_ln15_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_154_p4),79));
    zext_ln346_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_V_fu_140_p4),9));
    zext_ln818_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_224_p3),32));
end behav;
