set SynModuleInfo {
  {SRCNAME MLP_Pipeline_1 MODELNAME MLP_Pipeline_1 RTLNAME MLP_MLP_Pipeline_1
    SUBMODULES {
      {MODELNAME MLP_flow_control_loop_pipe_sequential_init RTLNAME MLP_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME MLP_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME MLP_Pipeline_2 MODELNAME MLP_Pipeline_2 RTLNAME MLP_MLP_Pipeline_2}
  {SRCNAME MLP_Pipeline_3 MODELNAME MLP_Pipeline_3 RTLNAME MLP_MLP_Pipeline_3}
  {SRCNAME MLP_Pipeline_4 MODELNAME MLP_Pipeline_4 RTLNAME MLP_MLP_Pipeline_4}
  {SRCNAME MLP_Pipeline_5 MODELNAME MLP_Pipeline_5 RTLNAME MLP_MLP_Pipeline_5}
  {SRCNAME MLP_Pipeline_6 MODELNAME MLP_Pipeline_6 RTLNAME MLP_MLP_Pipeline_6}
  {SRCNAME MLP_Pipeline_VITIS_LOOP_58_1 MODELNAME MLP_Pipeline_VITIS_LOOP_58_1 RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_58_1}
  {SRCNAME MLP_Pipeline_VITIS_LOOP_69_2 MODELNAME MLP_Pipeline_VITIS_LOOP_69_2 RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_69_2
    SUBMODULES {
      {MODELNAME MLP_fptrunc_64ns_32_2_no_dsp_1 RTLNAME MLP_fptrunc_64ns_32_2_no_dsp_1 BINDTYPE op TYPE fptrunc IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME MLP_ddiv_64ns_64ns_64_22_no_dsp_1 RTLNAME MLP_ddiv_64ns_64ns_64_22_no_dsp_1 BINDTYPE op TYPE ddiv IMPL fabric LATENCY 21 ALLOW_PRAGMA 1}
      {MODELNAME MLP_sitodp_32ns_64_4_no_dsp_1 RTLNAME MLP_sitodp_32ns_64_4_no_dsp_1 BINDTYPE op TYPE sitodp IMPL auto LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME MLP_Pipeline_VITIS_LOOP_77_3 MODELNAME MLP_Pipeline_VITIS_LOOP_77_3 RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3
    SUBMODULES {
      {MODELNAME MLP_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME MLP_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MLP_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME MLP_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_0_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_1_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_2_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_3_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_4_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_5_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_6_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_6_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_7_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_7_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_8_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_8_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_9_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_9_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_10_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_10_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_11_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_11_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_12_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_12_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_13_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_13_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_14_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_14_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_15_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_15_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_16_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_16_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_17_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_17_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_18_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_18_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_19_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_19_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_20_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_20_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_21_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_21_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_22_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_22_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_23_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_23_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_24_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_24_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_25_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_25_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_26_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_26_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_27_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_27_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_28_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_28_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_29_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_29_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_30_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_30_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_31_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_31_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_32_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_32_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_33_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_33_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_34_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_34_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_35_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_35_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_36_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_36_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_37_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_37_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_38_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_38_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_39_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_39_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_40_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_40_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_41_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_41_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_42_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_42_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_43_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_43_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_44_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_44_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_45_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_45_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_46_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_46_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_47_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_weights_1_47_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_hidden_bias_1_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_77_3_hidden_bias_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME MLP_Pipeline_VITIS_LOOP_94_5 MODELNAME MLP_Pipeline_VITIS_LOOP_94_5 RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5
    SUBMODULES {
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_0_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_1_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_2_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_3_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_4_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_5_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_6_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_6_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_7_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_7_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_8_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_8_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_9_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_9_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_10_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_10_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_11_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_11_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_12_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_12_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_13_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_13_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_14_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_14_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_15_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_15_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_16_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_16_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_17_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_17_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_18_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_18_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_19_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_19_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_20_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_20_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_21_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_21_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_22_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_22_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_23_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_weights_2_23_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_hidden_bias_2_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_94_5_hidden_bias_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME MLP_Pipeline_VITIS_LOOP_111_7 MODELNAME MLP_Pipeline_VITIS_LOOP_111_7 RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7
    SUBMODULES {
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_0_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_1_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_2_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_3_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_4_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_5_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_6_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_6_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_7_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_7_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_8_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_8_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_9_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_9_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_10_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_10_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_11_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_weights_11_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_bias_ROM_AUTO_1R RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_111_7_output_bias_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME MLP_Pipeline_VITIS_LOOP_123_9 MODELNAME MLP_Pipeline_VITIS_LOOP_123_9 RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_123_9}
  {SRCNAME MLP_Pipeline_VITIS_LOOP_128_10 MODELNAME MLP_Pipeline_VITIS_LOOP_128_10 RTLNAME MLP_MLP_Pipeline_VITIS_LOOP_128_10}
  {SRCNAME MLP MODELNAME MLP RTLNAME MLP IS_TOP 1
    SUBMODULES {
      {MODELNAME MLP_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME MLP_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME MLP_input_features_RAM_AUTO_1R1W RTLNAME MLP_input_features_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_input_features_casted_RAM_AUTO_1R1W RTLNAME MLP_input_features_casted_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_hidden_layer_1_RAM_AUTO_1R1W RTLNAME MLP_hidden_layer_1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_hidden_layer_2_RAM_AUTO_1R1W RTLNAME MLP_hidden_layer_2_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_output_layer_RAM_AUTO_1R1W RTLNAME MLP_output_layer_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MLP_regslice_both RTLNAME MLP_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME MLP_regslice_both_U}
    }
  }
}
