// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MLP_MLP_Pipeline_VITIS_LOOP_123_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_layer_address0,
        output_layer_ce0,
        output_layer_q0,
        output_layer_casted_address0,
        output_layer_casted_ce0,
        output_layer_casted_we0,
        output_layer_casted_d0,
        grp_fu_2471_p_din0,
        grp_fu_2471_p_din1,
        grp_fu_2471_p_dout0,
        grp_fu_2471_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] output_layer_address0;
output   output_layer_ce0;
input  [31:0] output_layer_q0;
output  [2:0] output_layer_casted_address0;
output   output_layer_casted_ce0;
output   output_layer_casted_we0;
output  [31:0] output_layer_casted_d0;
output  [31:0] grp_fu_2471_p_din0;
output  [31:0] grp_fu_2471_p_din1;
input  [31:0] grp_fu_2471_p_dout0;
output   grp_fu_2471_p_ce;

reg ap_idle;
reg output_layer_ce0;
reg output_layer_casted_ce0;
reg output_layer_casted_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln123_fu_107_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] i_4_cast_fu_119_p1;
reg   [63:0] i_4_cast_reg_280;
reg   [63:0] i_4_cast_reg_280_pp0_iter1_reg;
reg   [63:0] i_4_cast_reg_280_pp0_iter2_reg;
reg   [63:0] i_4_cast_reg_280_pp0_iter3_reg;
reg   [63:0] i_4_cast_reg_280_pp0_iter4_reg;
reg   [31:0] output_layer_load_reg_290;
reg   [31:0] dc_reg_295;
wire    ap_block_pp0_stage0;
reg   [2:0] i_fu_64;
wire   [2:0] add_ln123_fu_113_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_4;
wire   [31:0] data_V_fu_129_p1;
wire   [22:0] p_Result_1_fu_150_p1;
wire   [24:0] mantissa_fu_154_p4;
wire   [7:0] xs_exp_V_fu_140_p4;
wire   [8:0] zext_ln346_fu_168_p1;
wire   [8:0] add_ln346_fu_172_p2;
wire   [7:0] sub_ln1512_fu_186_p2;
wire   [0:0] isNeg_fu_178_p3;
wire  signed [8:0] sext_ln1512_fu_192_p1;
wire   [8:0] ush_fu_196_p3;
wire  signed [31:0] sext_ln1488_fu_204_p1;
wire   [78:0] zext_ln15_fu_164_p1;
wire   [78:0] zext_ln1488_fu_208_p1;
wire   [78:0] r_V_fu_212_p2;
wire   [0:0] tmp_fu_224_p3;
wire   [78:0] r_V_1_fu_218_p2;
wire   [31:0] zext_ln818_fu_232_p1;
wire   [31:0] tmp_6_fu_236_p4;
wire   [31:0] val_fu_246_p3;
wire   [0:0] p_Result_s_fu_132_p3;
wire   [31:0] result_V_2_fu_254_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

MLP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln123_fu_107_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_64 <= add_ln123_fu_113_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_4_cast_reg_280_pp0_iter1_reg[2 : 0] <= i_4_cast_reg_280[2 : 0];
        output_layer_load_reg_290 <= output_layer_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        dc_reg_295 <= grp_fu_2471_p_dout0;
        i_4_cast_reg_280_pp0_iter2_reg[2 : 0] <= i_4_cast_reg_280_pp0_iter1_reg[2 : 0];
        i_4_cast_reg_280_pp0_iter3_reg[2 : 0] <= i_4_cast_reg_280_pp0_iter2_reg[2 : 0];
        i_4_cast_reg_280_pp0_iter4_reg[2 : 0] <= i_4_cast_reg_280_pp0_iter3_reg[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln123_fu_107_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_4_cast_reg_280[2 : 0] <= i_4_cast_fu_119_p1[2 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln123_fu_107_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_layer_casted_ce0 = 1'b1;
    end else begin
        output_layer_casted_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_layer_casted_we0 = 1'b1;
    end else begin
        output_layer_casted_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_layer_ce0 = 1'b1;
    end else begin
        output_layer_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_fu_113_p2 = (ap_sig_allocacmp_i_4 + 3'd1);

assign add_ln346_fu_172_p2 = ($signed(zext_ln346_fu_168_p1) + $signed(9'd385));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign data_V_fu_129_p1 = dc_reg_295;

assign grp_fu_2471_p_ce = 1'b1;

assign grp_fu_2471_p_din0 = output_layer_load_reg_290;

assign grp_fu_2471_p_din1 = 32'd1259902592;

assign i_4_cast_fu_119_p1 = ap_sig_allocacmp_i_4;

assign icmp_ln123_fu_107_p2 = ((ap_sig_allocacmp_i_4 == 3'd5) ? 1'b1 : 1'b0);

assign isNeg_fu_178_p3 = add_ln346_fu_172_p2[32'd8];

assign mantissa_fu_154_p4 = {{{{1'd1}, {p_Result_1_fu_150_p1}}}, {1'd0}};

assign output_layer_address0 = i_4_cast_fu_119_p1;

assign output_layer_casted_address0 = i_4_cast_reg_280_pp0_iter4_reg;

assign output_layer_casted_d0 = ((p_Result_s_fu_132_p3[0:0] == 1'b1) ? result_V_2_fu_254_p2 : val_fu_246_p3);

assign p_Result_1_fu_150_p1 = data_V_fu_129_p1[22:0];

assign p_Result_s_fu_132_p3 = data_V_fu_129_p1[32'd31];

assign r_V_1_fu_218_p2 = zext_ln15_fu_164_p1 << zext_ln1488_fu_208_p1;

assign r_V_fu_212_p2 = zext_ln15_fu_164_p1 >> zext_ln1488_fu_208_p1;

assign result_V_2_fu_254_p2 = (32'd0 - val_fu_246_p3);

assign sext_ln1488_fu_204_p1 = $signed(ush_fu_196_p3);

assign sext_ln1512_fu_192_p1 = $signed(sub_ln1512_fu_186_p2);

assign sub_ln1512_fu_186_p2 = (8'd127 - xs_exp_V_fu_140_p4);

assign tmp_6_fu_236_p4 = {{r_V_1_fu_218_p2[55:24]}};

assign tmp_fu_224_p3 = r_V_fu_212_p2[32'd24];

assign ush_fu_196_p3 = ((isNeg_fu_178_p3[0:0] == 1'b1) ? sext_ln1512_fu_192_p1 : add_ln346_fu_172_p2);

assign val_fu_246_p3 = ((isNeg_fu_178_p3[0:0] == 1'b1) ? zext_ln818_fu_232_p1 : tmp_6_fu_236_p4);

assign xs_exp_V_fu_140_p4 = {{data_V_fu_129_p1[30:23]}};

assign zext_ln1488_fu_208_p1 = $unsigned(sext_ln1488_fu_204_p1);

assign zext_ln15_fu_164_p1 = mantissa_fu_154_p4;

assign zext_ln346_fu_168_p1 = xs_exp_V_fu_140_p4;

assign zext_ln818_fu_232_p1 = tmp_fu_224_p3;

always @ (posedge ap_clk) begin
    i_4_cast_reg_280[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_280_pp0_iter1_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_280_pp0_iter2_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_280_pp0_iter3_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    i_4_cast_reg_280_pp0_iter4_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //MLP_MLP_Pipeline_VITIS_LOOP_123_9
